Se termino la funcionalidad de otorgar permisos a la aplicacion admin
TallerDeDesarrollo-UCB/Nahual-Atenticacion pull request #11
Opened 2020-11-08 15:42 UTC by JoseCarlosOliveraPeredo

2020-11-08 20:51 UTC, Kuko-CMLC requested changes

2020-11-08 20:51 UTC, Kuko-CMLC commented on src/app/services/usuarioServicio.js
>        if (aplicacion === "Nahual") acceso = "permisoNahual";
Seria mejor usar un Switch case en pero en otro metodo aparte para mantener el codigo mas limpio.

2020-11-08 20:51 UTC, Kuko-CMLC commented on src/app/services/usuarioServicio.js
>        throw new Error("No se especifico una aplicacion de origen");
Aplicación lleva acento y punto al final de la oración.

2020-11-08 20:52 UTC, JPC07 commented on src/app/services/usuarioServicio.js
> +      if (aplicacion === "Admin") acceso = "permisoAdmin";
Dentro de esta funcion hay conselo.logs en la linea 29 y 36. Ya que estan tranajndo con esta funcion, podrian quitar esa parte.

2020-11-08 23:59 UTC, JoseCarlosOliveraPeredo commented on src/app/services/usuarioServicio.js
>        throw new Error("No se especifico una aplicacion de origen");
Resuelto

2020-11-08 23:59 UTC, JoseCarlosOliveraPeredo commented on src/app/services/usuarioServicio.js
>        if (aplicacion === "Nahual") acceso = "permisoNahual";
Resuelto, gracias Manu

2020-11-09 00:00 UTC, JoseCarlosOliveraPeredo commented on src/app/services/usuarioServicio.js
> +      if (aplicacion === "Admin") acceso = "permisoAdmin";
Ya los quite, gracias Jey :)

2020-11-10 00:02 UTC, FidelRojas approved these changes

2020-11-10 15:24 UTC, PabloCanelas approved these changes

2020-11-10 21:31 UTC, merged