Se añadio el servicio, controlador y ruta para revocar acceso
TallerDeDesarrollo-UCB/Nahual-Atenticacion pull request #7
Opened 2020-11-06 02:50 UTC by melissafg

2020-11-06 15:28 UTC, GamalSerhanOporto approved these changes

2020-11-07 16:55 UTC, PabloCanelas approved these changes

2020-11-08 01:41 UTC, JoseCarlosOliveraPeredo approved these changes

2020-11-08 20:38 UTC, JPC07 commented on src/app/services/usuarioServicio.js
> +        usuarioEcontrado[permiso] = false;
Correrir la gramatica por usuarioEncontrado.

2020-11-08 20:43 UTC, JPC07 commented on src/controladores/usuarioController.js
>  module.exports = UsuarioController;
El nombre no deberia ser en español, hay un mix de idiomas. Podria ser UsuarioControlador.

2020-11-08 20:44 UTC, Kuko-CMLC requested changes, later dismissed
Deberiamos cambiar el nombre del archivo .js que dice "usuarioController" por "usuarioControlador"

2020-11-08 20:44 UTC, Kuko-CMLC commented on src/app/services/usuarioServicio.js
> +    switch (aplicacion) {
Podrias refactorizar esta parte y colocarlo en un metodo "SeleccionarAplicacion" que devuelva el nombre de la app, solo sugerencia. :D

2020-11-08 20:44 UTC, Kuko-CMLC commented on src/app/services/usuarioServicio.js
> +    const usuarioEcontrado = await UsuarioService.encontrarUsuarioPor(email);
Dice "usuarioEcontrado" deberia ser "usuarioEncontrado".

2020-11-08 20:44 UTC, Kuko-CMLC commented on src/controladores/usuarioController.js
> +  revocarAccesoAplicacion: async (req, res) => {
"req" y "res" podrian ser en español como "solicitud" y "respuesta".

2020-11-08 23:04 UTC, FidelRojas commented on src/app/services/usuarioServicio.js
> +    switch (aplicacion) {
no lo vemos necesario

2020-11-08 23:12 UTC, merged